### ISSUE TITLE
RuntimeError: index_select(): Expected dtype int64 for index

### ISSUE THREAD

**Issue by kevinGit777** [saikat107/Codit#2]
hi,
I run the initialize.sh and follow by python full_translation.py and I get this error 

### ERROR
`Traceback (most recent call last):
  File "full_translation.py", line 125, in <module>
    transform_structurally(structure_options, token_id_file)
  File "full_translation.py", line 36, in transform_structurally
    all_scores, _, all_trees = structure_translate(structure_opts, grammar, structure_opts.n_best)
  File "/home/hxw170013/APR/Codit/translate_structure.py", line 132, in translate_all
    all_scores, all_cands = translator.translate(
  File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 203, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 304, in translate_batch
    return self._translate_batch(batch, data)
  File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 577, in _translate_batch
    b.advance(out[:, j],
  File "/home/hxw170013/APR/Codit/onmt/translate/beam.py", line 138, in advance
    self.attn.append(attn_out.index_select(0, prev_k))

RuntimeError: index_select(): Expected dtype int64 for index
`

### REPRODUCE 
`cd Codit
./initialize.sh
python full_translation.py
`

Can you help me out with it? Thank you so much!

**Comment by kevinGit777** [comment]
I think it is caused by my older pytorch, what version are you using when you run it?

**Comment by uetestina** [comment]
not sure if still needed but this could be the same issue as https://github.com/wasiahmad/NeuralCodeSum/issues/16

**Comment by mahdi943** [comment]
> hi, I run the initialize.sh and follow by python full_translation.py and I get this error
> 
> ### ERROR
> `Traceback (most recent call last): File "full_translation.py", line 125, in transform_structurally(structure_options, token_id_file) File "full_translation.py", line 36, in transform_structurally all_scores, _, all_trees = structure_translate(structure_opts, grammar, structure_opts.n_best) File "/home/hxw170013/APR/Codit/translate_structure.py", line 132, in translate_all all_scores, all_cands = translator.translate( File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 203, in translate batch_data = self.translate_batch(batch, data, fast=self.fast) File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 304, in translate_batch return self._translate_batch(batch, data) File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 577, in _translate_batch b.advance(out[:, j], File "/home/hxw170013/APR/Codit/onmt/translate/beam.py", line 138, in advance self.attn.append(attn_out.index_select(0, prev_k))
> 
> RuntimeError: index_select(): Expected dtype int64 for index `
> 
> ### REPRODUCE
> `cd Codit ./initialize.sh python full_translation.py `
> 
> Can you help me out with it? Thank you so much!

Hi Kevin, did you fix this problem? I have the same issue. Thanks in advance.

**Comment by kevinGit777** [comment]
I could not remember but I think it is a version problem. Try different versions of PyTorch or other ML packages. Good luck!

> > hi, I run the initialize.sh and follow by python full_translation.py and I get this error
> > ### ERROR
> > `Traceback (most recent call last): File "full_translation.py", line 125, in transform_structurally(structure_options, token_id_file) File "full_translation.py", line 36, in transform_structurally all_scores, _, all_trees = structure_translate(structure_opts, grammar, structure_opts.n_best) File "/home/hxw170013/APR/Codit/translate_structure.py", line 132, in translate_all all_scores, all_cands = translator.translate( File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 203, in translate batch_data = self.translate_batch(batch, data, fast=self.fast) File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 304, in translate_batch return self._translate_batch(batch, data) File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 577, in _translate_batch b.advance(out[:, j], File "/home/hxw170013/APR/Codit/onmt/translate/beam.py", line 138, in advance self.attn.append(attn_out.index_select(0, prev_k))
> > RuntimeError: index_select(): Expected dtype int64 for index `
> > ### REPRODUCE
> > `cd Codit ./initialize.sh python full_translation.py `
> > Can you help me out with it? Thank you so much!
> 
> Hi Kevin, did you fix this problem? I have the same issue. Thanks in advance.

**Comment by kevinGit777** [comment]
> > hi, I run the initialize.sh and follow by python full_translation.py and I get this error
> > ### ERROR
> > `Traceback (most recent call last): File "full_translation.py", line 125, in transform_structurally(structure_options, token_id_file) File "full_translation.py", line 36, in transform_structurally all_scores, _, all_trees = structure_translate(structure_opts, grammar, structure_opts.n_best) File "/home/hxw170013/APR/Codit/translate_structure.py", line 132, in translate_all all_scores, all_cands = translator.translate( File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 203, in translate batch_data = self.translate_batch(batch, data, fast=self.fast) File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 304, in translate_batch return self._translate_batch(batch, data) File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 577, in _translate_batch b.advance(out[:, j], File "/home/hxw170013/APR/Codit/onmt/translate/beam.py", line 138, in advance self.attn.append(attn_out.index_select(0, prev_k))
> > RuntimeError: index_select(): Expected dtype int64 for index `
> > ### REPRODUCE
> > `cd Codit ./initialize.sh python full_translation.py `
> > Can you help me out with it? Thank you so much!
> 
> Hi Kevin, did you fix this problem? I have the same issue. Thanks in advance.

try following this page [setup](https://github.com/OpenNMT/OpenNMT-py#setup) again, it is been a time so not sure it gonna work

**Comment by mahdi943** [comment]
> > > hi, I run the initialize.sh and follow by python full_translation.py and I get this error
> > > ### ERROR
> > > `Traceback (most recent call last): File "full_translation.py", line 125, in transform_structurally(structure_options, token_id_file) File "full_translation.py", line 36, in transform_structurally all_scores, _, all_trees = structure_translate(structure_opts, grammar, structure_opts.n_best) File "/home/hxw170013/APR/Codit/translate_structure.py", line 132, in translate_all all_scores, all_cands = translator.translate( File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 203, in translate batch_data = self.translate_batch(batch, data, fast=self.fast) File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 304, in translate_batch return self._translate_batch(batch, data) File "/home/hxw170013/APR/Codit/onmt/translate/translator.py", line 577, in _translate_batch b.advance(out[:, j], File "/home/hxw170013/APR/Codit/onmt/translate/beam.py", line 138, in advance self.attn.append(attn_out.index_select(0, prev_k)) RuntimeError: index_select(): Expected dtype int64 for index `
> > > ### REPRODUCE
> > > `cd Codit ./initialize.sh python full_translation.py `
> > > Can you help me out with it? Thank you so much!
> > 
> > 
> > Hi Kevin, did you fix this problem? I have the same issue. Thanks in advance.
> 
> try following this page [setup](https://github.com/OpenNMT/OpenNMT-py#setup) again, it is been a time so not sure it gonna work

Thanks, I changed Torch and Torchtext versions, and it worked.
